name: Web Engr Gatekeeper & Security

# Tatakbo ito pag may nag-push o nag-Pull Request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # 1. Dependency Scanning (Galing sa requirement list mo)
    - name: Run Dependency Scan (pip-audit)
      run: |
        pip install pip-audit
        pip-audit || echo "Audit completed"

    # 2. Code Quality (Galing sa requirement list mo)
    - name: Run Code Quality Check (Flake8)
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # 3. Security Testing (Galing sa requirement list mo)
    - name: Run Security Scan (Bandit)
      run: |
        pip install bandit
        bandit -r app.py

    # 4. Ang Gatekeeper Test (Para sa Web Engr)
    - name: Run Automated Tests
      run: |
        pytest test_app.py
